import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import CardComponent from '@/components/Card';
import AppComponent from '@/components/App';
import { Card, Grid, Text, Row, Button } from "@nextui-org/react";

import contact_list from '@/data/contact_list.json'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>

        </div>

        <AppComponent />

        {/* <div className="grid-bottom-padding">
          <Grid sm={16} md={12}>
            <div className="grid-container">

              {contact_list.map((contact, i) => (
                <div key={i} className="grid-item">
                  <CardComponent firstName={contact.first_name} lastName={contact.last_name} phone={contact.phone_number} />
                </div>
              ))}


            </div>

          </Grid>
        </div> */}


      </main>

    </>
  )
}
